Repository Curate-Me/claco-client, pull requests merged in 2024-11, with the labels that each got.

#27 feat: iOS 스플래시 화면 구현
  index.html
  public/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
  public/splash_screens/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png
  public/splash_screens/iPhone_11__iPhone_XR_portrait.png
  public/splash_screens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png
  public/splash_screens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png
  public/splash_screens/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png
  public/splash_screens/iPhone_16_Plus__iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_portrait.png
  public/splash_screens/iPhone_16_Pro_Max_portrait.png
  public/splash_screens/iPhone_16_Pro_portrait.png
  public/splash_screens/iPhone_16__iPhone_15_Pro__iPhone_15__iPhone_14_Pro_portrait.png
  public/splash_screens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png
  public/splash_screens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png
  src/globals.css
  src/pages/Onboarding/UserRegistration/Concept/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Onboarding/UserRegistration/Nickname/page.tsx
  src/pages/Onboarding/UserRegistration/Price/page.tsx
  src/pages/Onboarding/UserRegistration/Profile/page.tsx
Labels: 🔗feature

#31 docs: Update README.md
  README.md
Labels: 📄docs

#33 feat: zustand 라이브러리 적용
  package.json
  src/libraries/index.tsx
  src/libraries/store/index.ts
  yarn.lock
Labels: 🔗feature

#35 feat: ticket registration publishing
  src/assets/svgs/StarRating.svg
  src/assets/svgs/download.svg
  src/assets/svgs/halfStarRating.svg
  src/assets/svgs/plus.svg
  src/assets/svgs/remove.svg
  src/assets/svgs/required.svg
  src/components/Review/ReviewCard/index.tsx
  src/components/Ticket/AudienceReview/KeywordTags/index.tsx
  src/components/Ticket/AudienceReview/ReviewContents/index.tsx
  src/components/Ticket/AudienceReview/ReviewQuestions/index.tsx
  src/components/Ticket/AudienceReview/StarRating/index.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/CategoryTag/index.tsx
  src/components/common/Concept/index.tsx
  src/components/common/Location/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Price/index.tsx
  src/components/common/Profile/index.tsx
  src/components/common/ReviewTag/index.tsx
  src/components/common/Search/Bar/index.tsx
  src/components/common/Search/Card/index.tsx
  src/globals.css
  src/pages/Onboarding/UserRegistration/Concept/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/const/index.ts
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Onboarding/UserRegistration/Price/page.tsx
  src/pages/Onboarding/UserRegistration/Profile/page.tsx
  src/pages/Review/[id]/page.tsx
  src/pages/ShowDetail/page.tsx
  src/pages/Ticket/Detail/page.tsx
  src/pages/Ticket/Download/page.tsx
  src/pages/Ticket/Review/page.tsx
  src/pages/Ticket/Title/page.tsx
  src/pages/Ticket/const/index.ts
  src/pages/Ticket/page.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
  src/types/calendar.ts
  src/types/feature.ts
  src/types/index.ts
  src/types/modal.ts
  src/types/onboarding.ts
  src/types/poster.ts
  src/types/review.ts
  src/types/ticket.ts
Labels: 🔗feature, 🎨style

#38 feat: onboarding republishing
  src/components/Onboarding/Registration/index.tsx
  src/pages/Onboarding/CompleteRegistration/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/const/index.ts
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/types/onboarding.ts
Labels: 🔗feature, 🎨style

#41 feat: 티켓 등록 화면 로직 수정
  src/assets/images/showReview.png
  src/components/common/Modal/index.tsx
  src/pages/Ticket/Detail/page.tsx
  src/pages/Ticket/Review/page.tsx
  src/pages/Ticket/page.tsx
  src/types/modal.ts
Labels: 🔗feature, 🎨style

#44 Feat/#40 clacobook page publishing
  package.json
  src/assets/fonts/Nonchalance Medium.woff
  src/assets/fonts/Nonchalance Medium.woff2
  src/assets/fonts/UnicaOne-Regular.woff
  src/assets/fonts/UnicaOne-Regular.woff2
  src/assets/images/ClacoBook/ClcaoBook_Gray.png
  src/assets/images/ClacoBook/ClcaoBook_Orange.png
  src/assets/images/ClacoBook/ClcaoBook_Pink.png
  src/assets/svgs/ClacoBook.svg
  src/assets/svgs/Claco_Main.svg
  src/assets/svgs/Claco_Ticket.svg
  src/assets/svgs/Edit.svg
  src/assets/svgs/RightArrow.svg
  src/assets/svgs/trash.svg
  src/components/Layout/Footer/index.tsx
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/Ticket/AudienceReview/KeywordTags/index.tsx
  src/components/Ticket/AudienceReview/ReviewQuestions/index.tsx
  src/components/Ticket/ClacoBook/index.tsx
  src/components/Ticket/Modal/CreateEdit/index.tsx
  src/components/Ticket/Modal/Delete/index.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/ClacoTicket/index.tsx
  src/components/common/Modal/index.tsx
  src/components/ui/radio-group.tsx
  src/globals.css
  src/libraries/toast/Toast.tsx
  src/pages/Login/page.tsx
  src/pages/Ticket/page.tsx
  src/pages/TicketBook/Ticket/Detail/page.tsx
  src/pages/TicketBook/Ticket/Download/page.tsx
  src/pages/TicketBook/Ticket/Review/page.tsx
  src/pages/TicketBook/Ticket/Search/page.tsx
  src/pages/TicketBook/const/index.ts
  src/pages/TicketBook/page.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
  src/types/modal.ts
  tailwind.config.js
  yarn.lock
Labels: 🔗feature, 🎨style

#46 Feat/#45 clacodetail publishing
  package.json
  src/assets/images/MyClacoTicket1.png
  src/assets/images/MyClacoTicket2.png
  src/assets/images/MyClacoTicket3.png
  src/assets/svgs/DownLoadBox.svg
  src/assets/svgs/dotsthree.svg
  src/components/Ticket/AudienceReview/KeywordTags/index.tsx
  src/components/Ticket/AudienceReview/ReviewQuestions/index.tsx
  src/components/Ticket/Modal/Delete/ClacoBook/index.tsx
  src/components/Ticket/Modal/Delete/ClacoTicket/index.tsx
  src/components/Ticket/Modal/DownLoad/index.tsx
  src/components/Ticket/Modal/Move/index.tsx
  src/components/common/ClacoTicket/index.tsx
  src/components/common/Modal/index.tsx
  src/components/ui/radio-group.tsx
  src/globals.css
  src/libraries/toast/Toast.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketBook/Ticket/Download/page.tsx
  src/pages/TicketBook/[id]/page.tsx
  src/pages/TicketBook/page.tsx
  src/pages/TicketCreate/Download/page.tsx
  src/pages/TicketCreate/Info/page.tsx
  src/pages/TicketCreate/Review/page.tsx
  src/pages/TicketCreate/Search/page.tsx
  src/pages/TicketCreate/const/index.ts
  src/routes/routePath.ts
  src/routes/router.tsx
  yarn.lock
Labels: 🔗feature, 🎨style

#49 feat: browse page publishing
  index.html
  src/assets/images/poster13.png
  src/assets/svgs/CompletePreference.svg
  src/assets/svgs/Heart.svg
  src/assets/svgs/X-icon.svg
  src/assets/svgs/filter.svg
  src/assets/svgs/refresh.svg
  src/components/Browse/ClacoPick/ClacoPickShow/index.tsx
  src/components/Browse/ClacoPick/index.tsx
  src/components/Browse/ShowFilter/ShowFeatureFilter/index.tsx
  src/components/Browse/ShowFilter/index.tsx
  src/components/Layout/Footer/index.tsx
  src/components/Onboarding/Registration/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Calendar/CalendarDay/index.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/Concept/index.tsx
  src/components/common/Location/index.tsx
  src/components/common/Profile/index.tsx
  src/components/common/Search/Bar/index.tsx
  src/components/common/ShowFilterTab/index.tsx
  src/components/common/ShowSummaryCard/index.tsx
  src/globals.css
  src/hooks/useDebouncedState.ts
  src/pages/Browse/page.tsx
  src/pages/Onboarding/CompleteRegistration/page.tsx
  src/pages/Onboarding/UserRegistration/Concept/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/const/index.ts
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Onboarding/UserRegistration/Nickname/page.tsx
  src/pages/Onboarding/UserRegistration/Price/page.tsx
  src/pages/Onboarding/UserRegistration/Profile/page.tsx
  src/pages/TicketCreate/Search/page.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
  src/types/calendar.ts
  src/types/index.ts
  src/types/show.ts
  src/types/ticket.ts
Labels: 🔗feature, 🎨style

#50 feat: mypage publishing
  package.json
  src/assets/images/MagnifierBackground.png
  src/assets/lotties/onboarding-loading.json
  src/assets/svgs/Edit.svg
  src/assets/svgs/UserProfile.svg
  src/assets/svgs/listen.svg
  src/assets/svgs/settings.svg
  src/components/Layout/Footer/index.tsx
  src/components/Mypage/LikedShow/index.tsx
  src/components/Mypage/PreferenceAnalysis/PreferenceSettings/index.tsx
  src/components/Mypage/PreferenceAnalysis/index.tsx
  src/components/Mypage/UserSettings/index.tsx
  src/components/ShowDetail/AudienceReviews/ReviewSummaryCard/index.tsx
  src/components/ShowDetail/AudienceReviews/index.tsx
  src/components/ShowDetail/RelatedShowRecommend/index.tsx
  src/components/ShowDetail/ReviewSummaryCard/index.tsx
  src/components/ShowDetail/ShowInformation/ReservationRatio/index.tsx
  src/components/ShowDetail/ShowInformation/ShowEssentials/index.tsx
  src/components/ShowDetail/ShowInformation/ShowOverview/index.tsx
  src/components/ShowDetail/ShowInformation/ShowPoster/index.tsx
  src/components/Ticket/AudienceReview/StarRating/index.tsx
  src/components/common/Age/index.tsx
  src/components/common/Gender/index.tsx
  src/components/common/Nickname/index.tsx
  src/components/common/Profile/index.tsx
  src/pages/Mypage/page.tsx
  src/pages/Onboarding/CompleteRegistration/page.tsx
  src/pages/Onboarding/UserRegistration/Concept/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Onboarding/UserRegistration/Nickname/page.tsx
  src/pages/Onboarding/UserRegistration/Price/page.tsx
  src/pages/Onboarding/UserRegistration/Profile/page.tsx
  src/pages/ShowDetail/page.tsx
  src/pages/TicketBook/page.tsx
  src/pages/TicketCreate/Download/page.tsx
  src/pages/TicketCreate/Info/page.tsx
  src/pages/TicketCreate/Review/page.tsx
  src/pages/TicketCreate/Search/page.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
  src/types/index.ts
  src/types/onboarding.ts
  src/types/preference.ts
  src/types/ticket.ts
  yarn.lock
Labels: 🔗feature, 🎨style

#51 Feat/#47 clacoticket detail publishing
  src/apis/index.ts
  src/assets/images/ClacoBook/ClcaoBook_Gray.png
  src/assets/images/ClacoBook/ClcaoBook_Orange.png
  src/assets/images/ClacoBook/ClcaoBook_Pink.png
  src/assets/svgs/Edit.svg
  src/components/Browse/ClacoPick/index.tsx
  src/components/Browse/ShowFilter/index.tsx
  src/components/Layout/Footer/index.tsx
  src/components/Main/Analysis/AIRecommend/index.tsx
  src/components/Main/Analysis/SimilarKeyWordRecommend/index.tsx
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/Main/ClassicalPalette/index.tsx
  src/components/Mypage/LikedShow/index.tsx
  src/components/Mypage/PreferenceAnalysis/index.tsx
  src/components/Review/ReviewCard/const/index.ts
  src/components/Review/ReviewCard/index.tsx
  src/components/Ticket/AudienceReview/ReviewContents/ImageReview/index.tsx
  src/components/Ticket/AudienceReview/ReviewContents/TextReview/index.tsx
  src/components/Ticket/AudienceReview/ReviewContents/index.tsx
  src/components/Ticket/PerformanceAttributes/index.tsx
  src/components/Ticket/const/index.ts
  src/components/common/CategoryTag/index.tsx
  src/components/common/ClacoAnalysisCard/index.tsx
  src/components/common/ClacoTicket/index.tsx
  src/components/common/Genre/index.tsx
  src/components/common/Modal/ThumbnailModal/index.tsx
  src/components/common/Search/Bar/index.tsx
  src/components/common/Search/Card/index.tsx
  src/components/common/Search/HighLight/index.tsx
  src/components/common/ShowFilterTab/index.tsx
  src/components/common/ShowSummaryCard/const/index.ts
  src/components/common/ShowSummaryCard/index.tsx
  src/hooks/useDebouncedState.ts
  src/hooks/useShowFilter.ts
  src/hooks/useThumbnailModal.ts
  src/libraries/store/user.ts
  src/pages/Browse/page.tsx
  src/pages/Login/Kakao/AfterOnBoarding/page.tsx
  src/pages/Login/Kakao/BeforeOnBoarding/page.tsx
  src/pages/Login/page.tsx
  src/pages/Review/[id]/page.tsx
  src/pages/Review/page.tsx
  src/pages/Ticket/[id]/edit/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketBook/[id]/page.tsx
  src/pages/TicketCreate/Review/page.tsx
  src/pages/TicketCreate/Search/page.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
  src/types/index.ts
  src/types/layout.ts
  src/types/review.ts
  src/types/ticket.ts
Labels: 🔗feature, 🎨style

#53 feat: onboarding api
  src/apis/index.ts
  src/components/Mypage/PreferenceAnalysis/PreferenceSettings/index.tsx
  src/components/common/Age/index.tsx
  src/components/common/Gender/index.tsx
  src/components/common/Nickname/index.tsx
  src/hooks/useNickNameCheck.ts
  src/hooks/useUserInformationSubmit.ts
  src/libraries/store/onboarding.ts
  src/libraries/store/user.ts
  src/pages/Login/Kakao/AfterOnBoarding/page.tsx
  src/pages/Login/page.tsx
  src/pages/Onboarding/CompleteRegistration/page.tsx
  src/pages/Onboarding/UserRegistration/Concept/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Onboarding/UserRegistration/Nickname/page.tsx
  src/pages/Onboarding/UserRegistration/Price/page.tsx
  src/pages/Onboarding/UserRegistration/Profile/page.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
  src/types/onboarding.ts
Labels: 🌐api, 🔗feature

#55 feat: 48 axios instance
  src/apis/client.ts
  src/apis/index.ts
  src/apis/nickNameCheck.ts
  src/apis/submitUserInformation.ts
  src/assets/fonts/Nonchalance-Medium.woff
  src/assets/fonts/Nonchalance-Medium.woff2
  src/components/Browse/ShowFilter/index.tsx
  src/components/Main/Analysis/AIRecommend/index.tsx
  src/components/Main/Analysis/SimilarKeyWordRecommend/index.tsx
  src/components/Main/Analysis/TicketRecommend/Reviews/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/Main/MainPosterCard/index.tsx
  src/components/Mypage/LikedShow/index.tsx
  src/components/Review/ReviewCard/index.tsx
  src/components/ShowDetail/ShowInformation/ShowOverview/index.tsx
  src/components/Ticket/PerformanceAttributes/index.tsx
  src/components/common/ClacoAnalysisCard/index.tsx
  src/components/common/ClacoTicket/index.tsx
  src/components/common/Genre/index.tsx
  src/components/common/Nickname/index.tsx
  src/globals.css
  src/hooks/index.ts
  src/hooks/mutation/index.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useGetItemBased.ts
  src/hooks/queries/useGetUserBased.ts
  src/hooks/queries/useGetUserPreferences.ts
  src/hooks/useUserInformationSubmit.ts
  src/hooks/utils/index.ts
  src/hooks/utils/useDebouncedState.ts
  src/hooks/utils/useShowFilter.ts
  src/hooks/utils/useThumbnailModal.ts
  src/hooks/utils/useTruncateText.ts
  src/libraries/reactQuery/ReactQuerySetting.tsx
  src/pages/Browse/page.tsx
  src/pages/Login/Kakao/AfterOnBoarding/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/pages/Review/[id]/page.tsx
  src/pages/Review/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketCreate/Search/page.tsx
  src/routes/AuthenticatedLayout.tsx
  src/routes/router.tsx
  src/types/genre.ts
  src/types/preference.ts
Labels: 🌐api, 🔗feature

#58 feat: 공연 상세 페이지 api 연동
  src/components/Main/Analysis/SimilarKeyWordRecommend/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/Main/MainPosterCard/index.tsx
  src/components/ShowDetail/AudienceReviews/ReviewSummaryCard/index.tsx
  src/components/ShowDetail/AudienceReviews/index.tsx
  src/components/ShowDetail/RelatedShowRecommend/index.tsx
  src/components/ShowDetail/ShowInformation/ReservationRatio/index.tsx
  src/components/ShowDetail/ShowInformation/ShowEssentials/index.tsx
  src/components/ShowDetail/ShowInformation/ShowOverview/index.tsx
  src/components/ShowDetail/ShowInformation/ShowPoster/index.tsx
  src/components/common/CategoryTag/index.tsx
  src/components/common/Search/Card/index.tsx
  src/components/common/ShowSummaryCard/index.tsx
  src/hooks/mutation/index.ts
  src/hooks/mutation/usePostLike.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useGetConcertBased.ts
  src/hooks/queries/useGetShowDetail.ts
  src/hooks/utils/extractDateRange.ts
  src/hooks/utils/extractPricesWithSeats.ts
  src/hooks/utils/extractSchedule.ts
  src/hooks/utils/index.ts
  src/hooks/utils/timeToMinutes.ts
  src/pages/Review/page.tsx
  src/pages/ShowDetail/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/types/poster.ts
  src/types/show.ts
Labels: 🌐api, 🔗feature

#60 Feat/#57 search api
  package.json
  src/apis/client.ts
  src/components/Main/Analysis/SimilarKeyWordRecommend/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/Main/MainPosterCard/index.tsx
  src/components/Mypage/LikedShow/index.tsx
  src/components/ShowDetail/RelatedShowRecommend/index.tsx
  src/components/ShowDetail/ShowInformation/ShowOverview/index.tsx
  src/components/common/CategoryTag/index.tsx
  src/components/common/Search/Card/index.tsx
  src/components/common/ShowFilterTab/index.tsx
  src/components/common/ShowSummaryCard/const/index.ts
  src/components/common/ShowSummaryCard/index.tsx
  src/components/ui/skeleton.tsx
  src/globals.css
  src/hooks/queries/index.ts
  src/hooks/queries/useGetAutoCompleteSearch.ts
  src/hooks/queries/useGetConcertList.ts
  src/hooks/queries/useGetRecommendClacoTicket.ts
  src/hooks/queries/useGetSearch.ts
  src/hooks/utils/extractDateRange.ts
  src/hooks/utils/formatYYYYMMDD.ts
  src/hooks/utils/index.ts
  src/pages/Browse/page.tsx
  src/pages/Review/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketBook/page.tsx
  src/pages/TicketCreate/Info/page.tsx
  src/pages/TicketCreate/Search/page.tsx
  src/types/index.ts
  src/types/poster.ts
  src/types/preference.ts
  src/types/search.ts
  src/types/show.ts
  src/types/ticket.ts
  yarn.lock
Labels: 🌐api, 🔗feature

#62 Hotfix/#1 svg build error
  src/components/Ticket/AudienceReview/StarRating/index.tsx
Labels: 🐞bugfix

#65 feat: concert review api
  package.json
  src/assets/svgs/home.svg
  src/components/Browse/ClacoPick/index.tsx
  src/components/Browse/RecentConcertResult/index.tsx
  src/components/Browse/SearchResult/index.tsx
  src/components/Browse/ShowFilter/index.tsx
  src/components/Layout/Footer/index.tsx
  src/components/Main/Analysis/TicketRecommend/Reviews/index.tsx
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/Main/MainPosterCard/index.tsx
  src/components/Review/ReviewCard/index.tsx
  src/components/ShowDetail/ShowInformation/ShowOverview/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/CategoryTag/index.tsx
  src/components/common/Modal/ThumbnailModal/index.tsx
  src/components/common/Nickname/index.tsx
  src/components/common/ShowSummaryCard/index.tsx
  src/hooks/queries/index.ts
  src/hooks/queries/useGetAutoCompleteSearch.ts
  src/hooks/queries/useGetConcertFilters.ts
  src/hooks/queries/useGetConcertList.ts
  src/hooks/queries/useGetConcertReviewDetail.ts
  src/hooks/queries/useGetConcertReviewList.ts
  src/hooks/queries/useGetConcertReviewSize.ts
  src/hooks/queries/useGetSearch.ts
  src/hooks/utils/index.ts
  src/hooks/utils/useDeferredLoading.ts
  src/hooks/utils/useRefFocusEffect.ts
  src/hooks/utils/useThumbnailModal.ts
  src/libraries/reactQuery/ReactQuerySetting.tsx
  src/libraries/store/concertInfo.ts
  src/pages/Browse/page.tsx
  src/pages/Review/[id]/page.tsx
  src/pages/Review/page.tsx
  src/types/modal.ts
  src/types/preference.ts
  src/types/review.ts
  src/types/search.ts
  src/types/show.ts
  yarn.lock
Labels: 🌐api, 🔗feature

#66 feat: 티켓 등록 페이지 api 연동
  src/apis/index.ts
  src/apis/useGetPlaceCategories.ts
  src/apis/useGetTagCategories.ts
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/ShowDetail/AudienceReviews/ReviewSummaryCard/index.tsx
  src/components/ShowDetail/AudienceReviews/index.tsx
  src/components/ShowDetail/ShowInformation/ShowPoster/index.tsx
  src/components/Ticket/AudienceReview/KeywordTags/index.tsx
  src/components/Ticket/AudienceReview/ReviewContents/ImageReview/index.tsx
  src/components/Ticket/AudienceReview/ReviewContents/TextReview/index.tsx
  src/components/Ticket/AudienceReview/ReviewQuestions/index.tsx
  src/components/Ticket/AudienceReview/StarRating/index.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/ClacoTicket/index.tsx
  src/hooks/mutation/index.ts
  src/hooks/mutation/usePostTicketReview.ts
  src/hooks/mutation/usePutTicketImage.ts
  src/hooks/queries/useGetClacoBookList.ts
  src/hooks/queries/useGetTicketReviewDetail.ts
  src/hooks/utils/extractSchedule.ts
  src/hooks/utils/extractShowTime.tsx
  src/pages/Mypage/page.tsx
  src/pages/ShowDetail/page.tsx
  src/pages/TicketBook/[id]/page.tsx
  src/pages/TicketBook/page.tsx
  src/pages/TicketCreate/Download/page.tsx
  src/pages/TicketCreate/Info/page.tsx
  src/pages/TicketCreate/Review/page.tsx
  src/pages/TicketCreate/Search/page.tsx
  src/pages/TicketCreate/const/index.ts
  src/types/calendar.ts
  src/types/category.ts
  src/types/index.ts
  src/types/review.ts
  src/types/ticket.ts
Labels: 🌐api, 🔗feature

#70 feat: clacobook ticket api
  package.json
  src/apis/client.ts
  src/assets/images/Genre/grand.png
  src/assets/images/Genre/lyrical.png
  src/assets/images/Genre/modern.png
  src/components/Browse/ClacoPick/index.tsx
  src/components/Browse/RecentConcertResult/index.tsx
  src/components/Main/Analysis/AIRecommend/index.tsx
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/Main/MainPosterCard/index.tsx
  src/components/Ticket/ClacoBook/index.tsx
  src/components/Ticket/Modal/Move/index.tsx
  src/components/Ticket/PerformanceAttributes/index.tsx
  src/components/common/ClacoAnalysisCard/index.tsx
  src/components/common/ClacoTicket/index.tsx
  src/hooks/mutation/index.ts
  src/hooks/mutation/useDeleteClacoBook.ts
  src/hooks/mutation/useDeleteClacoTicket.ts
  src/hooks/mutation/usePostCreateClacoBook.ts
  src/hooks/mutation/usePostLike.ts
  src/hooks/mutation/usePostTicketReview.ts
  src/hooks/mutation/usePutEditClacoBook.ts
  src/hooks/mutation/usePutEditTicketReview.ts
  src/hooks/mutation/usePutMoveClacoTicket.ts
  src/hooks/mutation/usePutTicketImage.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useGetClacoTicketList.ts
  src/hooks/queries/useGetConcertFilters.ts
  src/hooks/queries/useGetConcertList.ts
  src/hooks/queries/useGetSearch.ts
  src/libraries/store/reviewInfo.ts
  src/pages/Browse/page.tsx
  src/pages/Ticket/[id]/edit/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketBook/[id]/page.tsx
  src/pages/TicketBook/page.tsx
  src/pages/TicketCreate/Download/page.tsx
  src/pages/TicketCreate/Review/page.tsx
  src/types/review.ts
  src/types/search.ts
  src/types/ticket.ts
  yarn.lock
Labels: 🌐api, 🔗feature

#73 feat: skeleton UI
  src/apis/useGetShowPosterUrl.ts
  src/assets/lotties/onboarding-loading.json
  src/components/Mypage/LikedShow/index.tsx
  src/hooks/mutation/usePostShowPoster.ts
  src/hooks/mutation/usePutTicketImage.ts
  src/pages/Mypage/page.tsx
  src/pages/ShowDetail/page.tsx
  src/pages/TicketBook/page.tsx
  src/pages/TicketCreate/Download/page.tsx
  src/pages/TicketCreate/Info/page.tsx
  src/pages/TicketCreate/Review/page.tsx
Labels: 🔗feature

#74 docs: update README.md
  .github/readme-assets/ai-flow.png
  .github/readme-assets/architecture.png
  .github/readme-assets/cicd.png
  .github/readme-assets/erd.png
  .github/readme-assets/server-test.png
  .github/readme-assets/test-coverage.png
  README.md
Labels: 📄docs

#75 docs: readme update
  README.md
Labels: 📄docs

#76 feat: qa/1 issue
  src/apis/client.ts
  src/assets/images/MyClacoTicket1.png
  src/assets/images/MyClacoTicket2.png
  src/assets/images/MyClacoTicket3.png
  src/assets/images/kakao.png
  src/assets/images/poster1.gif
  src/assets/images/poster10.gif
  src/assets/images/poster10_detail.jpg
  src/assets/images/poster11.gif
  src/assets/images/poster12.gif
  src/assets/images/poster13.png
  src/assets/images/poster2.gif
  src/assets/images/poster3.webp
  src/assets/images/poster4.gif
  src/assets/images/poster5.gif
  src/assets/images/poster6.gif
  src/assets/images/poster7.gif
  src/assets/images/poster8.gif
  src/assets/images/poster9.gif
  src/assets/images/profile.png
  src/assets/images/review.png
  src/components/Browse/RecentConcertResult/index.tsx
  src/components/Browse/SearchResult/index.tsx
  src/components/Browse/ShowFilter/index.tsx
  src/components/Main/Analysis/AIRecommend/index.tsx
  src/components/Main/Analysis/TicketRecommend/Reviews/index.tsx
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/common/Location/index.tsx
  src/components/common/Modal/index.tsx
  src/globals.css
  src/hooks/mutation/usePutTicketImage.ts
  src/hooks/queries/useGetConcertFilters.ts
  src/hooks/queries/useGetConcertList.ts
  src/hooks/utils/formatYYYYMMDD.ts
  src/hooks/utils/index.ts
  src/pages/Browse/page.tsx
  src/pages/Login/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketBook/[id]/page.tsx
  src/pages/TicketCreate/Download/page.tsx
  src/types/onboarding.ts
  src/types/search.ts
Labels: 🐞bugfix, 🌐api, 🔗feature

#77 depoly: 빌드 테스트 후 배포 서버 반영
  .github/readme-assets/ai-flow.png
  .github/readme-assets/architecture.png
  .github/readme-assets/cicd.png
  .github/readme-assets/erd.png
  .github/readme-assets/server-test.png
  .github/readme-assets/test-coverage.png
  README.md
  src/apis/client.ts
  src/apis/useGetShowPosterUrl.ts
  src/assets/images/MyClacoTicket1.png
  src/assets/images/MyClacoTicket2.png
  src/assets/images/MyClacoTicket3.png
  src/assets/images/kakao.png
  src/assets/images/poster1.gif
  src/assets/images/poster10.gif
  src/assets/images/poster10_detail.jpg
  src/assets/images/poster11.gif
  src/assets/images/poster12.gif
  src/assets/images/poster13.png
  src/assets/images/poster2.gif
  src/assets/images/poster3.webp
  src/assets/images/poster4.gif
  src/assets/images/poster5.gif
  src/assets/images/poster6.gif
  src/assets/images/poster7.gif
  src/assets/images/poster8.gif
  src/assets/images/poster9.gif
  src/assets/images/profile.png
  src/assets/images/review.png
  src/assets/lotties/onboarding-loading.json
  src/components/Browse/RecentConcertResult/index.tsx
  src/components/Browse/SearchResult/index.tsx
  src/components/Browse/ShowFilter/index.tsx
  src/components/Main/Analysis/AIRecommend/index.tsx
  src/components/Main/Analysis/TicketRecommend/Reviews/index.tsx
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/Mypage/LikedShow/index.tsx
  src/components/common/Location/index.tsx
  src/components/common/Modal/index.tsx
  src/globals.css
  src/hooks/mutation/usePostShowPoster.ts
  src/hooks/mutation/usePutTicketImage.ts
  src/hooks/queries/useGetConcertFilters.ts
  src/hooks/queries/useGetConcertList.ts
  src/hooks/utils/formatYYYYMMDD.ts
  src/hooks/utils/index.ts
  src/pages/Browse/page.tsx
  src/pages/Login/page.tsx
  src/pages/Mypage/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/ShowDetail/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketBook/[id]/page.tsx
  src/pages/TicketBook/page.tsx
  src/pages/TicketCreate/Download/page.tsx
  src/pages/TicketCreate/Info/page.tsx
  src/pages/TicketCreate/Review/page.tsx
  src/types/onboarding.ts
  src/types/search.ts
Labels: 🌏deploy

#80 feat: QA
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/pages/Login/page.tsx
  src/pages/TicketCreate/Download/page.tsx
Labels: 🔗feature

#81 Feat/#78 qa2 handling
  src/components/Browse/ShowFilter/index.tsx
  src/components/Main/Analysis/TicketRecommend/Reviews/index.tsx
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/common/Location/index.tsx
  src/hooks/mutation/usePutUserPreference.ts
  src/pages/Mypage/PreferenceEdit/page.tsx
  src/pages/Ticket/[id]/edit/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketBook/[id]/page.tsx
  src/pages/TicketBook/page.tsx
  src/routes/router.tsx
  src/types/onboarding.ts
Labels: 🐞bugfix, 🔗feature

#82 depoly: 빌드 테스트 후 배포 서버에 반영
  src/components/Browse/ShowFilter/index.tsx
  src/components/Main/Analysis/TicketRecommend/Reviews/index.tsx
  src/components/Main/Analysis/TicketRecommend/index.tsx
  src/components/common/Location/index.tsx
  src/hooks/mutation/usePutUserPreference.ts
  src/pages/Login/page.tsx
  src/pages/Mypage/PreferenceEdit/page.tsx
  src/pages/Ticket/[id]/edit/page.tsx
  src/pages/Ticket/[id]/page.tsx
  src/pages/TicketBook/[id]/page.tsx
  src/pages/TicketBook/page.tsx
  src/pages/TicketCreate/Download/page.tsx
  src/routes/router.tsx
  src/types/onboarding.ts
Labels: 🌏deploy

#84 fix: null 값 여부에 따라 뒤로가기 로직 구분
  src/pages/Ticket/[id]/page.tsx
Labels: 🐞bugfix

#85 depoly: 핫픽스 에러 수정
  src/pages/Ticket/[id]/page.tsx
Labels: 🐞bugfix, 🌏deploy

#87 fix: 좋아요 쿼리 캐싱 무효화
  src/hooks/mutation/usePostLike.ts
Labels: 🐞bugfix, 🌏deploy

#88 depoly: 좋아요 기능 수정 후 재배포
  src/hooks/mutation/usePostLike.ts
Labels: 🐞bugfix, 🌏deploy

#90 fix: 빈 클라코북 오류 처리
  src/pages/TicketBook/[id]/page.tsx
Labels: 🐞bugfix

#91 depoly: 빈 클라코북 에러 처리 후 배포
  src/pages/TicketBook/[id]/page.tsx
Labels: 🌏deploy

#93 depoly: 디자인 에러 수정
  src/pages/TicketBook/[id]/page.tsx
Labels: 🌏deploy

#94 fix: 디자인 수정
  src/pages/TicketBook/[id]/page.tsx
Labels: 🐞bugfix

#95 depoly: 재배포
  src/pages/TicketBook/[id]/page.tsx
Labels: 🌏deploy

#99 feat: QA 4차
  src/components/common/Search/Bar/index.tsx
  src/globals.css
  src/pages/Browse/page.tsx
  vite.config.ts
Labels: 🔗feature
