Repository Curate-Me/claco-client, pull requests merged in 2024-12, with the labels that each got.

#115 depoly: qa 5차 수정 후 배포
  src/components/Browse/ShowFilter/index.tsx
  src/components/Ticket/Modal/Move/index.tsx
  src/hooks/queries/useGetConcertFilters.ts
  src/pages/TicketBook/[id]/page.tsx
Labels: 🔗feature, 🌏deploy

#116 feat: 리프레쉬 쿠키 api 연동
  src/apis/client.ts
  src/apis/index.ts
  src/apis/refreshToken.ts
  src/pages/Login/Kakao/AfterOnBoarding/page.tsx
  src/pages/Login/Kakao/BeforeOnBoarding/page.tsx
Labels: 🔗feature

#117 deploy: 리프레쉬 쿠키 api 연동 후 배포
  src/apis/client.ts
  src/apis/index.ts
  src/apis/refreshToken.ts
  src/pages/Login/Kakao/AfterOnBoarding/page.tsx
  src/pages/Login/Kakao/BeforeOnBoarding/page.tsx
Labels: 🌏deploy

#118 feat: 리프레쉬 api 연동 수정
  src/apis/client.ts
  src/pages/Login/Kakao/AfterOnBoarding/page.tsx
  src/pages/Login/Kakao/BeforeOnBoarding/page.tsx
Labels: 🔗feature

#120 fix: axios 헤더 수정
  src/apis/client.ts
Labels: 🐞bugfix

#122 feat: 프로필 이미지 api 연동 수정
  src/pages/Mypage/UserEdit/page.tsx
Labels: 🔗feature

#123 deploy: 배포
  src/pages/Mypage/UserEdit/page.tsx
Labels: 🌏deploy

#124 feat: 마이페이지 리렌더링
  src/pages/Mypage/page.tsx
Labels: 🔗feature

#125 deploy: 배포
  src/pages/Mypage/page.tsx
Labels: 🌏deploy

#127 deploy: 배포
  src/apis/client.ts
  src/apis/index.ts
  src/apis/refreshToken.ts
  src/pages/Login/Kakao/AfterOnBoarding/page.tsx
  src/pages/Login/Kakao/BeforeOnBoarding/page.tsx
Labels: 🌏deploy
