Repository Curate-Me/claco-client, pull requests merged in 2024-10, with the labels that each got.

#8 fix: 로컬 폰트 추가
  src/assets/fonts/Pretendard-Bold.subset.woff
  src/assets/fonts/Pretendard-Bold.subset.woff2
  src/assets/fonts/Pretendard-Medium.subset.woff
  src/assets/fonts/Pretendard-Medium.subset.woff2
  src/assets/fonts/Pretendard-Regular.subset.woff
  src/assets/fonts/Pretendard-Regular.subset.woff2
  src/assets/fonts/Pretendard-SemiBold.subset.woff
  src/assets/fonts/Pretendard-SemiBold.subset.woff2
  src/assets/svgs/BackArrow.svg
  src/components/Main/MainPosterCard/index.tsx
  src/globals.css
  src/libraries/index.tsx
Labels: ⚙️settings

#9 feat/#2 onboarding publishing
  package.json
  src/assets/images/loading.gif
  src/assets/images/loginbackground.png
  src/assets/images/logo.png
  src/assets/svgs/BackArrow.svg
  src/assets/svgs/agreeIcon.svg
  src/assets/svgs/check.svg
  src/assets/svgs/checked.svg
  src/assets/svgs/errorIcon.svg
  src/components/Layout/Footer/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/Main/MainPosterCard/index.tsx
  src/components/Onboarding/Registration/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Genre/index.tsx
  src/components/ui/progress.tsx
  src/globals.css
  src/pages/Login/page.tsx
  src/pages/Main/containers/NearbyEventsSection.tsx
  src/pages/Main/containers/SimilarCollectionSection.tsx
  src/pages/Main/containers/SimilarShowsSection.tsx
  src/pages/Onboarding/CompleteRegistration/page.tsx
  src/pages/Onboarding/UserRegistration/Concept/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/const/index.ts
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Onboarding/UserRegistration/Nickname/page.tsx
  src/pages/Onboarding/UserRegistration/Price/page.tsx
  src/pages/Onboarding/UserRegistration/Profile/page.tsx
  src/pages/Tos/page.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
  src/types/feature.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🔗feature, 🎨style

#12 fix: 온보딩 버튼 오류 수정
  src/pages/Onboarding/UserRegistration/Concept/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Onboarding/UserRegistration/Nickname/page.tsx
  src/pages/Onboarding/UserRegistration/Profile/page.tsx
  src/pages/Tos/page.tsx
Labels: 🔗feature

#13 feat/#3 review publishing
  package.json
  src/assets/images/profile.png
  src/assets/images/review.png
  src/assets/svgs/BackArrow.svg
  src/assets/svgs/Fresh.svg
  src/assets/svgs/Like.svg
  src/assets/svgs/Lyrical.svg
  src/assets/svgs/Majestic.svg
  src/assets/svgs/StarRating.svg
  src/components/Layout/Footer/index.tsx
  src/components/Main/InformationCard/index.tsx
  src/components/Review/ReviewCard/index.tsx
  src/components/common/CategoryTag/index.tsx
  src/components/common/Genre/index.tsx
  src/components/common/ReviewTag/index.tsx
  src/components/common/ScrollTop/index.tsx
  src/globals.css
  src/pages/Main/containers/NearbyEventsSection.tsx
  src/pages/Main/containers/PersonalizedSection.tsx
  src/pages/Main/containers/SimilarShowsSection.tsx
  src/pages/Main/page.tsx
  src/pages/Onboarding/CompleteRegistration/page.tsx
  src/pages/Review/[id]/page.tsx
  src/pages/Review/page.tsx
  src/pages/ShowDetail/page.tsx
  src/routes/routePath.ts
  src/routes/router.tsx
  src/types/index.ts
  src/types/layout.ts
  src/types/poster.ts
  src/types/review.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🔗feature, 🎨style

#16 deploy: 배포 파일 생성
  build.sh
  vercel.json
Labels: 🌏deploy

#18 test: 자동 빌드 테스트
  src/pages/Review/page.tsx
Labels: 🌏deploy, 📘test

#19 feat: detail publishing
  package.json
  src/assets/images/poster10_detail.jpg
  src/assets/svgs/Book.svg
  src/assets/svgs/Female.svg
  src/assets/svgs/Heart.svg
  src/assets/svgs/Male.svg
  src/assets/svgs/Megaphone.svg
  src/components/Onboarding/Registration/index.tsx
  src/components/ShowDetail/ReviewSummaryCard/index.tsx
  src/components/common/Genre/index.tsx
  src/globals.css
  src/pages/Onboarding/UserRegistration/Concept/page.tsx
  src/pages/Onboarding/UserRegistration/Feature/page.tsx
  src/pages/Onboarding/UserRegistration/Location/page.tsx
  src/pages/Onboarding/UserRegistration/Nickname/page.tsx
  src/pages/Onboarding/UserRegistration/Price/page.tsx
  src/pages/Onboarding/UserRegistration/Profile/page.tsx
  src/pages/ShowDetail/containers/DetailsInfoSection.tsx
  src/pages/ShowDetail/containers/RelatedShowsSection.tsx
  src/pages/ShowDetail/containers/ReservationRatioSection.tsx
  src/pages/ShowDetail/containers/ReviewSection.tsx
  src/pages/ShowDetail/containers/ShowInfoSection.tsx
  src/pages/ShowDetail/containers/TopShowInfoSection.tsx
  src/pages/ShowDetail/page.tsx
  src/routes/router.tsx
  src/types/genre.ts
  src/types/review.ts
  yarn.lock
Labels: 🔗feature, 🎨style

#21 fix: 상세 정보 탭 활성화 로직 수정
  src/pages/Onboarding/UserRegistration/Nickname/page.tsx
  src/pages/ShowDetail/containers/DetailsInfoSection.tsx
  src/pages/ShowDetail/page.tsx
Labels: 🔗feature

#22 Feat/#14 review thumbnail
  src/assets/svgs/X-icon.svg
  src/components/Review/ReviewCard/const/index.ts
  src/components/Review/ReviewCard/index.tsx
  src/globals.css
  src/pages/Review/[id]/page.tsx
  src/pages/Review/page.tsx
  src/types/review.ts
Labels: 🔗feature

#24 Feat/#23 apply pwa
  index.html
  package.json
  public/icons/apple-touch-icon-114x114.png
  public/icons/apple-touch-icon-152x152.png
  public/icons/apple-touch-icon-180x180.png
  public/icons/apple-touch-icon-60x60.png
  public/icons/favicon-16x16.png
  public/icons/favicon-196x196.png
  public/icons/favicon-32x32.png
  public/icons/favicon-96x96.png
  public/icons/favicon.ico
  public/icons/logo.svg
  public/icons/maskable-icon-512x512.png
  public/icons/mstile-150x150.png
  public/icons/mstile-310x310.png
  public/icons/mstile-70x70.png
  public/icons/pwa-192x192.png
  public/icons/pwa-512x512.png
  public/icons/pwa-64x64.png
  public/manifest.json
  public/vite.svg
  src/components/Layout/Footer/index.tsx
  src/components/common/Genre/index.tsx
  src/pages/Login/page.tsx
  tsconfig.node.json
  yarn.lock
Labels: 🔗feature

#25 deploy: pwa 세팅 배포 서버에 반영
  index.html
  package.json
  public/icons/apple-touch-icon-114x114.png
  public/icons/apple-touch-icon-152x152.png
  public/icons/apple-touch-icon-180x180.png
  public/icons/apple-touch-icon-60x60.png
  public/icons/favicon-16x16.png
  public/icons/favicon-196x196.png
  public/icons/favicon-32x32.png
  public/icons/favicon-96x96.png
  public/icons/favicon.ico
  public/icons/logo.svg
  public/icons/maskable-icon-512x512.png
  public/icons/mstile-150x150.png
  public/icons/mstile-310x310.png
  public/icons/mstile-70x70.png
  public/icons/pwa-192x192.png
  public/icons/pwa-512x512.png
  public/icons/pwa-64x64.png
  public/manifest.json
  public/vite.svg
  src/components/Layout/Footer/index.tsx
  src/components/common/Genre/index.tsx
  src/pages/Login/page.tsx
  tsconfig.node.json
  yarn.lock
Labels: 🌏deploy
